name: UserFrosting
highlighter: pygments
url: http://v3.userfrosting.com
title: UserFrosting
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

theme: jekyll-theme-slate